[package]
name = "rust_esp"
version = "0.1.5"
edition = "2021"

[dependencies]
anyhow      = "=1.0.97"
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }

